### ISSUE TITLE
running the script from outside the folder fails

### ISSUE THREAD

**Issue by kheina** [DariusMiu/Slack-Dark-Mode#5]
```
> python3 non-work/Slack-Dark-Mode/darkmode.py
Traceback (most recent call last):
  File "non-work/Slack-Dark-Mode/darkmode.py", line 203, in <module>
    getattr(sys.modules[__name__], method)()
  File "non-work/Slack-Dark-Mode/darkmode.py", line 118, in install
    jsmod = createJavascript() + """
  File "non-work/Slack-Dark-Mode/darkmode.py", line 101, in createJavascript
    with open('replacements.json', 'r') as replacementfile :
FileNotFoundError: [Errno 2] No such file or directory: 'replacements.json'
```

retrieve replacements.json from executable's directory rather than console active directory

**Comment by kheina** [comment]
`__location__ = os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__)))`
